var mongoose = require('mongoose');
var GameSchema = new mongoose.Schema({
    name: String,
    player1: String,
    player1_ships: String,
    player1_board: String,
    player2: String,
    player2_ships: String,
    player2_board: String,
    history: [String],
    status: {type: String, default: 'setup'} //setup, p1_turn, p2_turn, finished
});

var ShipSchema = new mongoose.Schema({
    game_id: String,
    player_id: String,
    battleship_position: String, //number ex. 01, 35, 99, etc
    battleship_location: String, //up, down, left, right
    carrier_position: String,
    carrier_location: String,
    cruiser_position: String,
    cruiser_location: String,
    submarine_position: String,
    submarine_location: String,
    destroyer_position: String,
    destroyer_location: String
});

var BoardSchema = new mongoose.Schema({
    game_id: String,
    player_id: String,
    C00: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C01: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C02: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C03: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C04: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C05: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C06: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C07: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C08: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C09: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C10: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C11: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C12: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C13: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C14: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C15: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C16: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C17: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C18: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C19: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C20: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C21: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C22: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C23: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C24: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C25: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C26: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C27: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C28: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C29: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C30: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C31: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C32: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C33: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C34: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C35: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C36: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C37: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C38: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C39: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C40: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C41: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C42: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C43: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C44: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C45: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C46: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C47: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C48: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C49: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C50: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C51: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C52: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C53: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C54: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C55: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C56: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C57: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C58: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C59: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C60: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C61: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C62: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C63: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C64: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C65: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C66: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C67: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C68: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C69: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C70: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C71: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C72: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C73: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C74: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C75: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C76: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C77: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C78: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C79: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C80: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C81: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C82: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C83: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C84: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C85: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C86: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C87: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C88: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C89: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C90: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C91: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C92: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C93: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C94: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C95: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C96: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C97: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C98: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}},
    C99: {type: {type: String, default: 'none'}, isOccupied: {type: Boolean, default: 'false'}, ship: {type: String, default: 'none'}}
});

var AccountSchema = new mongoose.Schema({
    name: String,
    email: String,
    user: String,
    pass: String,
    country: String,
    date: String
});

mongoose.model('Game', GameSchema);
mongoose.model('Ship', ShipSchema);
mongoose.model('Board', BoardSchema);
mongoose.model('Account', AccountSchema);
